coverage:
  status:
    project:
      default:
        informational: true # https://docs.codecov.com/docs/commit-status#informational
		patch:
      default:
        informational: true # https://docs.codecov.com/docs/commit-status#project-status

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false
