codecov:
  if_ci_failed: ignore # ignore, fail, pass
  informational: true

coverage:
  status:
    # Learn more at https://docs.codecov.io/docs/commit-status
    project:
      default:
        threshold: 1% # allow this much decrease on project

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false
