name: Pull Request

on: pull_request

jobs:
  test:
    name: "Tests"
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 16.7
        uses: actions/setup-node@v3
        with:
          node-version: 16.7
          cache: "npm" # cache ~/.npm in case 'npm ci' needs to run

      - name: Install NPM Dependencies
        run: npm ci

      - name: Run builds
        run: npm run build
        env:
          NODE_ENV: "production"

      - name: Run tests & collect coverage
        run: npm run test:ci

      - name: Report Code Coverage
        uses: codecov/codecov-action@v3
